[build]
builder = "nixpacks"
buildCommand = "cd urfadanhaber-backend && go build -o main ."

[deploy]
startCommand = "cd urfadanhaber-backend && ./main"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
